### ISSUE TITLE
ESP32 incompatible

### ISSUE THREAD

**Issue by JasonMorris1** [adafruit/Adafruit_VEML6075#2]
- Arduino board:  ESP32 dev board

- Arduino IDE version: 1.8.7

- The esp32 fails to connect with the Veml6075. I tried other sensors on my I2c pins on esp32 and they worked. I tried my Veml6075 with the adafruit library on a arduino uno and it worked.

**Comment by ladyada** [comment]
can you post a photo of your wiring?

**Comment by CheetahGod** [comment]
Sent from my T-Mobile 4G LTE Device
-------- Original message --------From: ladyada <notifications@github.com> Date: 10/7/18  10:52 PM  (GMT-08:00) To: adafruit/Adafruit_VEML6075 <Adafruit_VEML6075@noreply.github.com> Cc: CheetahGod <jasonbm123@gmail.com>, Author <author@noreply.github.com> Subject: Re: [adafruit/Adafruit_VEML6075] ESP32 incompatible (#2) 
can you post a photo of your wiring?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/adafruit/Adafruit_VEML6075","title":"adafruit/Adafruit_VEML6075","subtitle":"GitHub repository","main_image_url":"https://assets-cdn.github.com/images/email/message_cards/header.png","avatar_image_url":"https://assets-cdn.github.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/adafruit/Adafruit_VEML6075"}},"updates":{"snippets":[{"icon":"PERSON","message":"@ladyada in #2: can you post a photo of your wiring?"}],"action":{"name":"View Issue","url":"https://github.com/adafruit/Adafruit_VEML6075/issues/2#issuecomment-427727453"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/adafruit/Adafruit_VEML6075/issues/2#issuecomment-427727453",
"url": "https://github.com/adafruit/Adafruit_VEML6075/issues/2#issuecomment-427727453",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
},
{
"@type": "MessageCard",
"@context": "http://schema.org/extensions",
"hideOriginalBody": "false",
"originator": "AF6C5A86-E920-430C-9C59-A73278B5EFEB",
"title": "Re: [adafruit/Adafruit_VEML6075] ESP32 incompatible (#2)",
"sections": [
{
"text": "",
"activityTitle": "**Limor \"Ladyada\" Fried**",
"activityImage": "https://assets-cdn.github.com/images/email/message_cards/avatar.png",
"activitySubtitle": "@ladyada",
"facts": [

]
}
],
"potentialAction": [
{
"name": "Add a comment",
"@type": "ActionCard",
"inputs": [
{
"isMultiLine": true,
"@type": "TextInput",
"id": "IssueComment",
"isRequired": false
}
],
"actions": [
{
"name": "Comment",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueComment\",\n\"repositoryFullName\": \"adafruit/Adafruit_VEML6075\",\n\"issueId\": 2,\n\"IssueComment\": \"{{IssueComment.value}}\"\n}"
}
]
},
{
"name": "Close issue",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueClose\",\n\"repositoryFullName\": \"adafruit/Adafruit_VEML6075\",\n\"issueId\": 2\n}"
},
{
"targets": [
{
"os": "default",
"uri": "https://github.com/adafruit/Adafruit_VEML6075/issues/2#issuecomment-427727453"
}
],
"@type": "OpenUri",
"name": "View on GitHub"
},
{
"name": "Unsubscribe",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"MuteNotification\",\n\"threadId\": 389061942\n}"
}
],
"themeColor": "26292E"
}
]

**Comment by JasonMorris1** [comment]
![20181007_233637_crop_845x400](https://user-images.githubusercontent.com/22126616/46595053-6f37e880-ca8b-11e8-81ff-53a783d63651.jpg)

![20181007_233543](https://user-images.githubusercontent.com/22126616/46595004-24b66c00-ca8b-11e8-802b-838795f32f41.jpg)
![20181007_233602](https://user-images.githubusercontent.com/22126616/46595008-2a13b680-ca8b-11e8-8377-63ccc27fa7c2.jpg)
I tired using some pullup resistors but did not help. Going to experiment with more pullup resistors tomorrow

**Comment by ladyada** [comment]
ok can you try this one?
https://github.com/kriswiner/VEML6075/blob/master/VEML6075.basicexample.ino
or this one?
https://github.com/NorthernWidget/VEML6075

**Comment by JasonMorris1** [comment]
I tried the first one. Its still not working

**Comment by JasonMorris1** [comment]
Tried both. Still not working.

**Comment by ladyada** [comment]
ok i wired one up and yah it shows up asn an i2c device but all reads are 0 value!

**Comment by bisonburt** [comment]
Read my comments in the adafruit fourm:
https://forums.adafruit.com/viewtopic.php?f=8&t=141920&p=707818&hilit=veml6075#p707818


If all reads are 0's or some value that does not change over time, it's likely an issue with the version/state of your IDE. I can get the VEML6075 working with an esp32 (HUZZAH32 and my custom esp32 PCB) with my Arduino IDE 1.8.3 version but not with a new install of 1.8.7.  My 1.8.3 IDE is using the early esp32 setup before they integrated it into the IDE using the boards manager. Looks like something changed.

**Comment by ladyada** [comment]
i belive this is fixed in latest commit, but you'll have to manually install BusIO library which we will be using
https://github.com/adafruit/Adafruit_BusIO
if it still doesnt work, plz reopen issue
